import { Geist, Geist_Mono, Oswald } from "next/font/google";
import { Merienda } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { FloatingButtons } from "./component/Floating";
import Footer from "./component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
  weight: ["400", "700"], // adjust if you need bold
});
const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-oswald',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merienda.variable} ${oswald.variable} antialiased`}
        style={{
          fontFamily: 'var(--font-oswald)',
          letterSpacing: '0.05em',
        }}
      >
        <Navbar />

        {children}
        <FloatingButtons />
        <Footer />
      </body>
    </html>
  );
}
